openapi: 3.1.0
x-stoplight:
  id: 4d65f2a7sccv0
info:
  title: schema
  version: "1.0"
  description: sns-app OpenAPI schema
  license:
    name: unlicense
    identifier: Unlicense
  contact:
    name: na2na
    email: na2na@na2na.dev
    url: "https://github.com/na2na-p/sns-app"
servers:
  - url: "http://localhost/api/v1"
paths:
  /ping:
    get:
      summary: Your GET endpoint
      responses:
        "200":
          description: pong
      operationId: get-ping
      tags:
        - dev-only
      description: ping
    parameters: []
  /users:
    post:
      summary: ""
      operationId: sigin-up
      tags:
        - sign-up
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      description: Create user
      responses:
        "201":
          description: Example response
          content:
            application/json:
              schema:
                title: User
                type: object
                examples:
                  - userId: 00ccebbc13e070008b186150ad2d0c05
                    name: Alice Smith
                    email: hoge@example.com
                    created_at: "2023-01-13T10:33:15+9:00"
                    upddate_at: "2023-01-13T10:33:15+9:00"
                x-tags:
                  - users
                description: ユーザ
                properties:
                  userId:
                    type: string
                    description: ユーザID
                  name:
                    type: string
                    description: ユーザのニックネーム
                  email:
                    type: string
                    description: ユーザのemail
                required:
                  - userId
                  - name
                  - email
  /login:
    post:
      summary: ""
      operationId: login
      tags:
        - login
        - user
      description: for login use
      parameters:
        - schema:
            type: string
          in: cookie
          description: Laravel session Id
          required: true
          name: laravel_session
        - schema:
            type: string
          in: cookie
          name: X-XSRF-TOKEN
          description: Laravel Sanctum
          required: true
      responses:
        "200":
          description: Example response
          content:
            application/json:
              schema:
                title: User
                type: object
                examples:
                  - userId: 00ccebbc13e070008b186150ad2d0c05
                    name: Alice Smith
                    email: hoge@example.com
                    created_at: "2023-01-13T10:33:15+9:00"
                    upddate_at: "2023-01-13T10:33:15+9:00"
                x-tags:
                  - users
                description: ユーザ
                properties:
                  userId:
                    type: string
                    description: ユーザID
                  name:
                    type: string
                    description: ユーザのニックネーム
                  email:
                    type: string
                    description: ユーザのemail
                required:
                  - userId
                  - name
                  - email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
  /logout:
    post:
      summary: ""
      operationId: logout
      responses:
        "200":
          description: OK
      tags:
        - logout
      description: for logout use
  /messages:
    get:
      summary: Your GET endpoint
      tags:
        - message
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      title: Message
                      x-stoplight:
                        id: byjkqw35cpck1
                      type: object
                      description: メッセージ
                      x-tags:
                        - messages
                      examples:
                        - messageId: 00ccebbc13e070008b186150ad2d0c05
                          body: 山路を登りながら
                          created_at: "2023-01-13T10:33:15+9:00"
                          updated_at: "2023-01-13T10:33:15+9:00"
                          favorited: 123
                          isFavorited: true
                      properties:
                        messageId:
                          type: string
                        body:
                          type: string
                        created_at:
                          type: string
                        favorited:
                          type: integer
                        isFavorited:
                          type: boolean
                      required:
                        - messageId
                        - body
                        - created_at
                        - favorited
                        - isFavorited
                required:
                  - messages
      operationId: get-messages
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                lastMessageId:
                  type: string
                perPage:
                  type: string
                  description: default is 10
      description: for message fetch
    post:
      summary: ""
      operationId: post-message
      responses:
        "201":
          description: Example response
          content:
            application/json:
              schema:
                title: Message
                x-stoplight:
                  id: byjkqw35cpck1
                type: object
                description: メッセージ
                x-tags:
                  - messages
                examples:
                  - messageId: 00ccebbc13e070008b186150ad2d0c05
                    body: 山路を登りながら
                    created_at: "2023-01-13T10:33:15+9:00"
                    updated_at: "2023-01-13T10:33:15+9:00"
                    favorited: 123
                    isFavorited: true
                properties:
                  messageId:
                    type: string
                  body:
                    type: string
                  created_at:
                    type: string
                  favorited:
                    type: integer
                  isFavorited:
                    type: boolean
                required:
                  - messageId
                  - body
                  - created_at
                  - favorited
                  - isFavorited
            application/xml:
              schema:
                type: object
                properties: {}
      tags:
        - message
      description: for message post.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
                - body
  "/messages/{messageId}/favorite":
    parameters:
      - schema:
          type: string
        name: messageId
        in: path
        required: true
        description: messageId
    put:
      summary: ""
      operationId: favorite
      responses:
        "200":
          description: OK
      description: for favorite
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                isFavorited:
                  type: boolean
                  description: 操作後の状態を示す
              required:
                - isFavorited
        description: ""
      tags:
        - favorite
        - message
  "/users/{userId}/password":
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: userId
    put:
      summary: passwordUpdate
      operationId: passwordUpdate
      responses:
        "200":
          description: OK
      description: for password update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
              required:
                - password
      tags:
        - user
  "/users/{userId}":
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: userId
    put:
      summary: ""
      operationId: user-info-update
      responses:
        "200":
          description: Example response
          content:
            application/json:
              schema:
                title: User
                type: object
                examples:
                  - userId: 00ccebbc13e070008b186150ad2d0c05
                    name: Alice Smith
                    email: hoge@example.com
                    created_at: "2023-01-13T10:33:15+9:00"
                    upddate_at: "2023-01-13T10:33:15+9:00"
                x-tags:
                  - users
                description: ユーザ
                properties:
                  userId:
                    type: string
                    description: ユーザID
                  name:
                    type: string
                    description: ユーザのニックネーム
                  email:
                    type: string
                    description: ユーザのemail
                required:
                  - userId
                  - name
                  - email
      description: for user info update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
                - name
                - email
      tags:
        - user
tags:
  - name: dev-only
    description: 開発専用
  - name: favorite
    description: お気に入り関係
  - name: login
    description: ログイン用
  - name: logout
    description: ログアウト用
  - name: message
    description: メッセージ関係
  - name: sign-up
    description: 登録
  - name: user
    description: ユーザ関係
components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - userId: 00ccebbc13e070008b186150ad2d0c05
          name: Alice Smith
          email: hoge@example.com
          created_at: "2023-01-13T10:33:15+9:00"
          upddate_at: "2023-01-13T10:33:15+9:00"
      x-tags:
        - users
      description: ユーザ
      properties:
        userId:
          type: string
          description: ユーザID
        name:
          type: string
          description: ユーザのニックネーム
        email:
          type: string
          description: ユーザのemail
      required:
        - userId
        - name
        - email
    Message:
      title: Message
      x-stoplight:
        id: byjkqw35cpck1
      type: object
      description: メッセージ
      x-tags:
        - messages
      examples:
        - messageId: 00ccebbc13e070008b186150ad2d0c05
          body: 山路を登りながら
          created_at: "2023-01-13T10:33:15+9:00"
          updated_at: "2023-01-13T10:33:15+9:00"
          favorited: 123
          isFavorited: true
      properties:
        messageId:
          type: string
        body:
          type: string
        created_at:
          type: string
        favorited:
          type: integer
        isFavorited:
          type: boolean
      required:
        - messageId
        - body
        - created_at
        - favorited
        - isFavorited
  securitySchemes: {}
  responses:
    User:
      description: Example response
      content:
        application/json:
          schema:
            title: User
            type: object
            examples:
              - userId: 00ccebbc13e070008b186150ad2d0c05
                name: Alice Smith
                email: hoge@example.com
                created_at: "2023-01-13T10:33:15+9:00"
                upddate_at: "2023-01-13T10:33:15+9:00"
            x-tags:
              - users
            description: ユーザ
            properties:
              userId:
                type: string
                description: ユーザID
              name:
                type: string
                description: ユーザのニックネーム
              email:
                type: string
                description: ユーザのemail
            required:
              - userId
              - name
              - email
    Message:
      description: Example response
      content:
        application/json:
          schema:
            title: Message
            x-stoplight:
              id: byjkqw35cpck1
            type: object
            description: メッセージ
            x-tags:
              - messages
            examples:
              - messageId: 00ccebbc13e070008b186150ad2d0c05
                body: 山路を登りながら
                created_at: "2023-01-13T10:33:15+9:00"
                updated_at: "2023-01-13T10:33:15+9:00"
                favorited: 123
                isFavorited: true
            properties:
              messageId:
                type: string
              body:
                type: string
              created_at:
                type: string
              favorited:
                type: integer
              isFavorited:
                type: boolean
            required:
              - messageId
              - body
              - created_at
              - favorited
              - isFavorited
        application/xml:
          schema:
            type: object
            properties: {}
x-internal: false
