name: Cloudflare Pages Slide Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

env:
  BASE_URL: https://na2na-sns-app-slide.na2na.dev

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          make slide-build
      - name: Generate github token
        id: generate_token
        uses: ./.github/actions/github-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: na2na-sns-app-slide
          directory: ./packages/intern-slide/dist
          gitHubToken: ${{ steps.generate_token.outputs.token }}
  CachePurge:
    runs-on: ubuntu-latest
    needs: Publish
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PURGE_URLS: '["${{ env.BASE_URL }}", "${{ env.BASE_URL }}/"]'
