name: Frontend-Build-Test
on:
  push:
    branches-ignore:
      - main
jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        run: make setup-ci
      - name: Build
        run: make frontend-build
