name: Image Scan
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build images
        run: |
          make all-containers-build
      - name: PHP Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "backend-laravel.test:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      - name: Nginx Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "backend-nginx:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
