name: Auto Assign For Labeled P.R.

on:
  pull_request:
    types: [labeled]

jobs:
  approve:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: >-
      ${{
        github.event.label.name == 'Please Review' &&
        github.event.pull_request.user.login == 'na2na-p'
      }}
    env:
      NUMBER: ${{ github.event.number }}

    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
