name: Test(Backend)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  Test-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate github token
        id: generate_token
        uses: ./.github/actions/github-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Setup CI
        run: make setup-ci
      - name: Test
        run: make backend-test
      # - name: Hide Duplicate Comment with Coverage Summary
      #   if: github.event_name == 'pull_request'
      #   uses: kamatama41/hide-pr-comments-action@v0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     author: 2na2
      #     # Coverage after mergingから始まる正規表現
      #     message_regex: "Coverage after merging*"
      - name: Shaping
        if: github.event_name == 'pull_request'
        run: sed -i -e 's/\/var\/www\/html/packages\/backend/g' ./packages/backend/clover.xml
      - name: Coverage Summary
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/coverage
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          clover-file: ./packages/backend/clover.xml
  Lint-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        run: make setup-ci
      - name: Lint
        run: make backend-lint
