name: Test(Backend)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  Test-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        run: make setup-ci
      - name: Lint
        run: make backend-test
  Lint-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        run: make setup-ci
      - name: Lint
        run: make backend-lint
